# Generated by Django 2.1.7 on 2019-03-08 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True, verbose_name='いいねタイミング')),
                ('liked_by', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Likeユーザー')),
                ('tweet', models.ForeignKey(db_column='tweet_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='tweet.Tweet', verbose_name='つぶやき')),
            ],
        ),
    ]
