# Generated by Django 2.1.7 on 2019-03-08 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutter', models.CharField(max_length=140, verbose_name='つぶやき')),
                ('tweeted_at', models.DateTimeField(auto_now_add=True, verbose_name='つぶやきタイミング')),
                ('tweeted_by', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('tweeted_to', models.ForeignKey(db_column='tweetwd_to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweeted_by_s', to='tweet.Tweet', verbose_name='つぶやき先')),
            ],
        ),
    ]
