# Generated by Django 2.1.7 on 2019-03-09 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'verbose_name': 'tweet', 'verbose_name_plural': 'tweet'},
        ),
    ]
